// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArYxYxbwQjks5fIuuY-5ZyDUOuUnL1jxo',
    appId: '1:581146190372:android:5f6ed167100e809a2d6eb1',
    messagingSenderId: '581146190372',
    projectId: 'sharexe-c2071',
    databaseURL: 'https://sharexe-c2071-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sharexe-c2071.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHPaITZkBNPmusF6Its8-kvSdxZM3fKFw',
    appId: '1:581146190372:web:4237d01dcc5ed7f12d6eb1',
    messagingSenderId: '581146190372',
    projectId: 'sharexe-c2071',
    authDomain: 'sharexe-c2071.firebaseapp.com',
    databaseURL: 'https://sharexe-c2071-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sharexe-c2071.firebasestorage.app',
    measurementId: 'G-J7HVV9WBJ3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_fuH4AsXn1fqxjfAH4LLxkUUex9I7JJo',
    appId: '1:581146190372:ios:26a40fc6d56e45982d6eb1',
    messagingSenderId: '581146190372',
    projectId: 'sharexe-c2071',
    databaseURL: 'https://sharexe-c2071-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sharexe-c2071.firebasestorage.app',
    iosBundleId: 'com.example.sharexe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_fuH4AsXn1fqxjfAH4LLxkUUex9I7JJo',
    appId: '1:581146190372:ios:26a40fc6d56e45982d6eb1',
    messagingSenderId: '581146190372',
    projectId: 'sharexe-c2071',
    databaseURL: 'https://sharexe-c2071-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sharexe-c2071.firebasestorage.app',
    iosBundleId: 'com.example.sharexe',
  );
static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHPaITZkBNPmusF6Its8-kvSdxZM3fKFw',
    appId: '1:581146190372:web:2ad86b5364405f622d6eb1',
    messagingSenderId: '581146190372',
    projectId: 'sharexe-c2071',
    authDomain: 'sharexe-c2071.firebaseapp.com',
    databaseURL: 'https://sharexe-c2071-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sharexe-c2071.firebasestorage.app',
    measurementId: 'G-F77ZEFXMPH',
  );

}
